basePath: /
host: localhost:8080
info:
  contact:
    email: ricardo@goncalves.biz
    name: Ricardo Gonçalves
    url: https://goncalves.biz
  description: Product API with authentication
  termsOfService: https://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
